name: Create Infrastructure RDS

on:
  workflow_dispatch:

env:
 TF_CLOUD_ORGANIZATION: "postech-fiap"

jobs:
  terraform-apply-infra:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MEL }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MEL }}
          aws-region: us-east-1
   
      - run: terraform -chdir="./env/dev" init
        
      - run: terraform -chdir="./env/dev" apply -auto-approve

